config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  get 'dashboard', to: 'dashboard#index'
  root to: 'dashboard#index'
  resources :journals do
    resources :mood_options, only: [:new, :create]
  end

  resources :tasks do
    resources :mood_options, only: [:new, :create]
  end

  resources :tasks do
    patch :complete, on: :member, action: :update_status
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_one :mood_option, as: :optionable, dependent: :destroy
  validates :title, presence: true
  validates :status, inclusion: { in: ['未着手', '進行中', '完了'] }
  validates :priority, inclusion: { in: ['優先度３', '優先度２', '優先度１'] }

  enum status: { '未着手': 0, '進行中': 1, '完了': 2 }
  enum priority: { '優先度１': 0, '優先度２': 1, '優先度３': 2 }

  def status_in_japanese
    I18n.t("activerecord.attributes.task.status.#{status}")
  end

  def priority_in_japanese
    I18n.t("activerecord.attributes.task.priority.#{priority}")
  end
  # completed?メソッドを追加
  def completed?
    status == '完了'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = current_user.tasks.order(priority: :desc, due_date: :asc)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to new_task_mood_option_path(@task), notice: 'タスクを作成しました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to new_task_mood_option_path(@task), notice: 'タスクを更新しました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_status
    @task = Task.find(params[:id])
    new_status = params[:status]
    
    # 新しい状態でタスクを更新
    if @task.update(status: new_status)
      redirect_to dashboard_path, notice: "タスクの状態が更新されました"
    else
      redirect_to dashboard_path, alert: "タスクの状態更新に失敗しました"
    end
  end
  
  def destroy
    @task.destroy
    redirect_to root_path, notice: 'タスクを削除しました。'
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :status, :priority).merge(user_id: current_user.id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="task_edit">
  <%= form_with(model: @task, local: true) do |f| %>
    <div class="task_edit__form">
        <div class="edit_form__title">
          <%= f.text_field :title, placeholder: 'タスクを書こう', class: 'form_control__title', required: true, rows: 1, 
  cols: 82 %>
        </div>
        <div class="edit_form__description">
          <%= f.text_area :description, placeholder: 'タスクの詳細を書こう', class: 'form_control__description', rows: 6, 
  cols: 60 %>
        </div>
      <div class="edit_form__limits">
        <div class="edit_form__priority">
          <%= f.select :priority, Task.priorities.map { |key, _value| [Task.human_attribute_name("priority.#{key}"), key] }, {}, class: 'form_control__priority' %>
        </div>
        <div class="edit_form__due_date">
          <%= f.datetime_select :due_date, class: 'form_control__date' %> までのタスクが
        </div>
        <div class="edit_form__status">
          <%= f.select :status, Task.statuses.map { |key, _value| [Task.human_attribute_name("status.#{key}"), key] }, {}, class: 'form_control__status' %>です
        </div>
      </div>
    </div>
</div>
  <div class="task_edit__btn">
    <%= f.submit '次へ', class: 'btn_create' %>
  </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="task_edit__btn">
  <%= link_to '＜ 戻る', root_path, class: 'btn' %>
  <%= link_to '削除 ＞',"/tasks/#{@task.id}", data: {turbo_method: :delete}, class: 'btn' %>
</div>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>


<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>優先度</th>
      <th>締切日</th>
      <th>状態</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.priority %></td>
        <td><%= task.due_date %></td>
        <td><%= task.status %></td>
        <td>
          <%= link_to '詳細', task_path(task) %> |
          <%= link_to '編集', edit_task_path(task) %> |
          <%= link_to '削除', task_path(task), method: :delete, data: { confirm: '削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<!-- 新しいタスクを作成 -->
<div class="journal_edit__btn">
  <%= link_to '＜ 戻る', root_path, class: 'btn' %>
</div>
<%= render 'form', task: @task %>
<%= link_to '一覧に戻る', tasks_path, class: 'btn btn-secondary' %>

app/views/tasks/show.html.erb
<!-- タスク詳細 -->
<div class="task_show__btn">
  <%= link_to '＜ 戻る', root_path, class: 'btn' %>
  <%= link_to '編集 ＞', edit_task_path(@task), class: 'btn' %>
</div>
<div class="task_show">
  <div class="task_show__title">
    <%= @task.title %>
  </div>
  <div class="task_show__description">
    <%= @task.description %>
  </div>
  <div class="task_show__due_date">
    <%= @task.due_date.strftime('%Y-%m-%d %H:%M') %> まで
  </div>
  <!-- 
  <div class="task_show__priority">
    <%= @task.priority_in_japanese %>
  </div>
  <div class="task_show__status">
    <%= @task.status_in_japanese %>
  </div>
  -->
  <div style="task_show_moods">
    <% if @task.mood_option %>
      <%= @task.mood_option.labels.join(", ") %>
      <%#= @task.mood_option.colors.join %>
    <% end %>
  </div>
</div>