config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  get 'dashboard', to: 'dashboard#index'
  root to: 'dashboard#index'
  resources :journals do
    resources :mood_options, only: [:new, :create]
  end

  resources :tasks do
    resources :mood_options, only: [:new, :create]
  end

  resources :tasks do
    patch :complete, on: :member, action: :update_status
  end
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  has_one :mood_option, as: :optionable, dependent: :destroy

  validates :entry_date, presence: true
  validates :content,    presence: true
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:destroy, :edit, :update, :show]
  
  def index
    @journals = Journal.includes(:mood_option)
  end
  def new
    @journal = Journal.new
  end

  def create
    @journal = current_user.journals.build(journal_params)
    if @journal.save
      # ジャーナル作成後、ポリモーフィック関連で MoodOption の new アクションにリダイレクト
      redirect_to new_journal_mood_option_path(@journal), notice: 'ジャーナルを作成しました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @journal.destroy
      redirect_to root_path
    else
      redirect_to journals_url, status: :unprocessable_entity, notice: 'ジャーナルが削除されました。'
    end
  end

  def edit
  end

  def update
    if @journal.update(journal_params)
      redirect_to new_journal_mood_option_path(@journal), notice: 'ジャーナルを更新しました。'
    else
      render :edit, alert: '更新に失敗しました。'
    end
  end

  def show
    @journal = Journal.find(params[:id])
    # @mood_option = @journal.mood_option
  end

  private
  def set_journal
    @journal = Journal.find(params[:id])
  end
  
  def journal_params
    params.require(:journal).permit(:entry_date, :content).merge(user_id: current_user.id)
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<div class="journal_edit">
  <%= form_with(model: @journal, local: true) do |f| %>
    <div class="journal_edit__form">
      <div class="edit_form__date">
        <%= f.date_field :entry_date, class: 'form_control__date' %>
      </div>
    <div class="edit_form__content">
      <div class="form-control-container">
        <%= f.text_area :content, placeholder: '今の気持ちを書き出してみよう', class: 'form_control__content', rows: 6, 
  cols: 82 %>
      </div>
    </div>
    <div>
    <%= f.submit '次へ', class: 'btn_create' %>
    </div>
  <% end %>
</div>

app/views/journals/edit.html.erb
<div class="journal_edit__btn">
  <%= link_to '＜ 戻る', root_path, class: 'btn' %>
  <%= link_to '削除 ＞',"/journals/#{@journal.id}", data: {turbo_method: :delete}, class: 'btn' %>
</div>
<%= render 'form', journal: @journal %>

app/views/journals/index.html.erb
<!-- Journal一覧 -->
<table>
<thead>
<tr>
  <div class='account-page' id='account-page'>
    <p>こんにちは、<%= link_to current_user.nickname, edit_user_registration_path(current_user) %> さん！</p>
  </div>
</tr>
</thead>
<tbody>
<% @journals.each do |journal| %>
  <div class="journal-entry">
    <p><%= journal.entry_date %></p>
    <p><%= journal.content %></p>
    <% if journal.mood_option %>
      <p>Feelings: <%= journal.mood_option.labels.join(", ") %></p>
      <div style="display: flex;">
        <% journal.mood_option.colors.each do |color| %>
          <div style="width: 20px; height: 20px; background-color: <%= color %>;"></div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to '詳細', journal_path(journal) %>
<% end %>
</tbody>
</table>

<%= link_to '新規作成', new_journal_path %>

app/views/journals/new.html.erb
<!-- 新しいジャーナルを作成 -->
<div class="journal_edit__btn">
  <%= link_to '＜ 戻る', root_path, class: 'btn' %>
</div>
<%= render 'form', journal: @journal %>

app/views/journals/show.html.erb
<!-- ジャーナル詳細 -->
<div class="journal_show__btn">
  <%= link_to '＜ 戻る', root_path, class: 'btn' %>
  <%= link_to '編集 ＞', edit_journal_path(@journal), class: 'btn' %>
</div>
<div class="journal_show">
  <div class="journal_show__content">
    <%= @journal.content %>
  </div>
  <div class="journal_show__date">
    <%= @journal.entry_date %>
  </div>
  <div style="journal_show_moods">
    <%# if @journal.mood_option %>
      <div>
        <%= @journal.mood_option&.labels&.join(", ") || "ラベルはありません" %>
      </div>
      <div>
        <%# ( @journal.mood_option.colors || [] ).each do |color| %> <!-- nilの場合空配列を使う -->
          <div>
            <!-- <span style="background-color: <%#= color %>; width: 30px; height: 30px; display: inline-block; margin-right: 5px;"></span> -->
            <%#= color %> <!-- 色コードを表示 -->
          </div>
        <%# end %>
      </div>
    <%# end %>
  </div>
<!-- <p>
  <strong>気分:</strong>
  <% if @mood_option&.average_color %>
    <span style="background-color: <%= @mood_option.average_color %>; width: 20px; height: 20px; display: inline-block;"></span>
    <%= @mood_option.average_color %>
  <% else %>
    気分データがありません
  <% end %>
</p> -->
</div>