config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  get 'dashboard', to: 'dashboard#index'
  root to: 'dashboard#index'
  resources :journals do
    resources :mood_options, only: [:new, :create]
  end

  resources :tasks do
    resources :mood_options, only: [:new, :create]
  end

  resources :tasks do
    patch :complete, on: :member, action: :update_status
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KokoroTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag "mood_option", media: 'all' %>
    <!-- importmapを最初に読み込む -->
    <%= javascript_importmap_tags %> <!-- これを追加 -->
    <!-- モジュールスクリプトを読み込む -->
    <%= javascript_include_tag 'form_steps', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'controllers/form_steps_controller', 'data-turbolinks-track': 'reload' %>
    <!-- 
    <script src="/assets/form_steps.js"></script>
    <script src="/assets/controllers/form_steps_controller.js"></script>
    -->
  </head>

  <body>
    <div class="body__container">
    <% unless (controller_name == 'journals' && (action_name == 'show' || action_name == 'edit' || action_name == 'new')) || 
              (controller_name == 'tasks' && (action_name == 'show' || action_name == 'edit' || action_name == 'new')) || 
              (controller_name == 'mood_options' && (action_name == 'show' || action_name == 'edit' || action_name == 'new')) %>
	    <header class="header">
        <div class="header-content">
          <h1>ココロタスク</h1>
        </div>
      </header>
    <% end %>
      <%= yield %>
    <% unless (controller_name == 'journals' && (action_name == 'show' || action_name == 'edit' || action_name == 'new')) || 
              (controller_name == 'tasks' && (action_name == 'show' || action_name == 'edit' || action_name == 'new')) || 
              (controller_name == 'mood_options' && (action_name == 'show' || action_name == 'edit' || action_name == 'new')) %>
      <footer class="footer">
        <nav>
          <%#= link_to 'ダッシュボード', dashboard_path %>
          <%#= link_to 'ジャーナル一覧', journals_path %>
          <%#= link_to 'タスク一覧', tasks_path %>
        </nav>
      <p>© 2024 ココロタスク</p>
      </footer>
    <% end %>
    </div>
  </body>
</html>